### ISSUE TITLE
Full KMS no screen configuration available

### ISSUE THREAD

**Issue by audas** [raspberrypi-ui/arandr#1]
Using the latest firmware and latest OS with the vc4-kms-v3d driver the screen configuration utility does not appear - also when using the raspi-config utility I can not change the resolution.

**Comment by spl237** [comment]
That's deliberate - at present, KMS does not support the use of this tool, or the mechanism for changing resolution in raspi-config. The full KMS driver is experimental at present, and this is part of the reason why.
