### ISSUE TITLE
Raspberry Pi OS menu item for app doesn't match app title displayed in arandr's titlebar

### ISSUE THREAD

**Issue by andrum993** [raspberrypi-ui/arandr#4]
Just noticed that Raspberry Pi OS's menu calls the app `Screen Configuration`, but the app's own titlebar says `Screen Layout Editor`. Does this matter, and if so, should I file a PR?

**Comment by spl237** [comment]
No compulsion for those two to match, and arandr is going to be replaced in the near future anyway.
